# Generated by Django 3.2 on 2024-05-09 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20240509_0704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='description',
            field=models.TextField(max_length=256, null=True, verbose_name='Описание'),
        ),
    ]
