# Generated by Django 3.2 on 2024-06-11 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20240611_0744'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='name',
            field=models.TextField(default=0, max_length=256, verbose_name='Название'),
            preserve_default=False,
        ),
    ]
