# Generated by Django 3.2 on 2024-06-11 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_title_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='name',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='genre',
            name='name',
            field=models.CharField(default=0, max_length=256),
            preserve_default=False,
        ),
    ]
